development:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - high
  - default
  - mailers

:schedule:
  refresh_coin:
    every: 5s
    class: RefreshCoin
  refresh_leaderboard:
    every: 5s
    class: RefreshLeaderboard
  
